apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: gowebapp-backend
  template:
    metadata:
      labels:
        app: gowebapp-backend
    spec:
      containers:
        - name: gowebapp-backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: backend-config
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 15
            periodSeconds: 20