apiVersion: v1
kind: Service
metadata:
  name: gowebapp-frontend
spec:
  type: NodePort
  selector:
    app: gowebapp-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: 30080