backend:
  image: avinash1504/gowebapp-backend
  tag: v2
  port: 8081
  replicas: 2

frontend:
  image: avinash1504/gowebapp-frontend
  tag: v1
  port: 80
  replicas: 1

database:
  image: avinash1504/gowebapp-database
  tag: v1
  port: 5432
  replicas: 1
  password: password