apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gowebapp-backend
  template:
    metadata:
      labels:
        app: gowebapp-backend
    spec:
      containers:
        - name: gowebapp-backend
          image: avinash1504/gowebapp-backend:v2
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: backend-config
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20